export const IconsNames = {
	star: 'star',
	rectangle: 'rectangle',
	circle: 'circle',
	diagonal_arrow: 'diagonal_arrow',
	fork_knife: 'fork_knife',
	star1: 'star1',
	bag: 'bag',
	pin: 'pin',
	settings: 'settings',
	star_nav: 'star_nav',
	chat_nav: 'chat_nav',
	home_nav: 'home_nav',
	like_nav: 'like_nav',
	bell_nav: 'bell_nav',
};
